RUBOCOP ?= rubocop
CLANG_FORMAT ?= clang-format
PREFIX ?= /usr/local
MANPREFIX ?= ${PREFIX}/man
RELEASE = 3.2

RSET_COMPONENTS = rutils input execute worker rset_secrets
RSECRET_COMPONENTS = rsecret_config rsecret_memory rsecret_redis rsecret_gpg rsecret_scanner
RSET_OBJS = ${RSET_COMPONENTS:=.o} ${RSECRET_COMPONENTS:=.o} compat.o rset.o
RSET_INC = ${RSET_COMPONENTS:=.h} rsecret.h rsecret_scanner.h rset_secrets.h config.h missing/compat.h

RSECRET_OBJS = ${RSECRET_COMPONENTS:=.o} compat.o rsecret.o
RSECRET_INC = rsecret.h missing/compat.h

QUARK_COMPONENTS = sock http
QUARK_OBJS = ${QUARK_COMPONENTS:=.o} compat.o miniquark.o
QUARK_INC = ${QUARK_COMPONENTS:=.h} missing/compat.h

PROGS = rset rsecret miniquark rinstall rsub labelgrep renv rexec-summary

all: ${PROGS}

.c.o:
	${CC} ${CFLAGS} ${CPPFLAGS} -c $<

compat.c: missing/*
	cat /dev/null ${EXTRA_SRC} > compat.c

rset.o: ${RSET_INC} rset.c
	${CC} ${CFLAGS} ${CPPFLAGS} -DRELEASE=\"${RELEASE}\" -c rset.c

rset: ${RSET_COMPONENTS:=.h} ${RSET_OBJS}
	${CC} ${CFLAGS} ${CPPFLAGS} -o $@ ${RSET_OBJS} ${LDFLAGS}

rsecret.o: ${RSECRET_INC} rsecret.c
	${CC} ${CFLAGS} ${CPPFLAGS} -DRELEASE=\"${RELEASE}\" -c rsecret.c

rsecret: ${RSECRET_INC} ${RSECRET_OBJS}
	${CC} ${CFLAGS} ${CPPFLAGS} -o $@ ${RSECRET_OBJS} ${LDFLAGS}

miniquark.o: ${QUARK_INC} miniquark.c
	${CC} ${CFLAGS} ${CPPFLAGS} -DRELEASE=\"${RELEASE}\" -c miniquark.c

miniquark: ${QUARK_COMPONENTS:=.h} ${QUARK_OBJS}
	${CC} ${CFLAGS} ${CPPFLAGS} -o $@ ${QUARK_OBJS} ${LDFLAGS}

.sh:
	sed -e 's/$${release}/${RELEASE}/' $< > $@
	@chmod +x $@

.SUFFIXES: .awk
.awk:
	sed -e 's/$${release}/${RELEASE}/' $< > $@
	@chmod +x $@

install: ${PROGS}
	@mkdir -p ${DESTDIR}${PREFIX}/bin
	@mkdir -p ${DESTDIR}${MANPREFIX}/man1
	@mkdir -p ${DESTDIR}${MANPREFIX}/man5
	install -m 644 labelgrep.1 ${DESTDIR}${MANPREFIX}/man1
	install -m 644 miniquark.1 ${DESTDIR}${MANPREFIX}/man1
	install -m 644 pln.5 ${DESTDIR}${MANPREFIX}/man5
	install -m 644 renv.1 ${DESTDIR}${MANPREFIX}/man1
	install -m 644 rinstall.1 ${DESTDIR}${MANPREFIX}/man1
	install -m 644 rset.1 ${DESTDIR}${MANPREFIX}/man1
	install -m 644 rsecret.1 ${DESTDIR}${MANPREFIX}/man1
	install -m 644 rsub.1 ${DESTDIR}${MANPREFIX}/man1
	install labelgrep ${DESTDIR}${PREFIX}/bin
	install miniquark ${DESTDIR}${PREFIX}/bin
	install renv ${DESTDIR}${PREFIX}/bin
	install rexec-summary ${DESTDIR}${PREFIX}/bin
	install rinstall ${DESTDIR}${PREFIX}/bin
	install rset ${DESTDIR}${PREFIX}/bin
	install rsecret ${DESTDIR}${PREFIX}/bin
	install rsub ${DESTDIR}${PREFIX}/bin

uninstall:
	rm ${DESTDIR}${MANPREFIX}/man1/labelgrep.1
	rm ${DESTDIR}${MANPREFIX}/man1/miniquark.1
	rm ${DESTDIR}${MANPREFIX}/man1/renv.1
	rm ${DESTDIR}${MANPREFIX}/man1/rinstall.1
	rm ${DESTDIR}${MANPREFIX}/man1/rset.1
	rm ${DESTDIR}${MANPREFIX}/man1/rsecret.1
	rm ${DESTDIR}${MANPREFIX}/man1/rsub.1
	rm ${DESTDIR}${MANPREFIX}/man5/pln.5
	rm ${DESTDIR}${PREFIX}/bin/labelgrep
	rm ${DESTDIR}${PREFIX}/bin/miniquark
	rm ${DESTDIR}${PREFIX}/bin/renv
	rm ${DESTDIR}${PREFIX}/bin/rexec-summary
	rm ${DESTDIR}${PREFIX}/bin/rinstall
	rm ${DESTDIR}${PREFIX}/bin/rset
	rm ${DESTDIR}${PREFIX}/bin/rsecret
	rm ${DESTDIR}${PREFIX}/bin/rsub

test: ${PROGS}
	make -C tests

format:
	${RUBOCOP} -A
	${CLANG_FORMAT} -i *.c *.h tests/*.c missing/*.c missing/*.h

clean:
	rm -f compat.c *.o *.core ${PROGS}
	make -C tests clean

distclean:
	rm -f Makefile tests/Makefile
	rm -f *.lock

.PHONY: all clean distclean format install test uninstall
