.\"
.\" Copyright (c) 2025 Eric Radman <ericshane@eradman.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd January 6, 2025
.Dt RSECRET 1
.Os
.Sh NAME
.Nm rsecret
.Nd encrypted secret management for rset
.Sh SYNOPSIS
.Nm
.Op Fl c Ar config
.Fl g Ar key
.Nm
.Op Fl c Ar config
.Fl s Ar key Ar value
.Nm
.Op Fl c Ar config
.Fl l
.Nm
.Op Fl c Ar config
.Fl v Ar key1 key2 ...
.Sh DESCRIPTION
.Nm
manages encrypted secrets stored in Redis for use with
.Xr rset 1 .
Secrets are encrypted using GPG and stored with a Redis key prefix.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl c Ar config
Use alternate configuration file (default: rsecret.conf)
.It Fl g Ar key
Get and decrypt secret by key
.It Fl s Ar key Ar value
Encrypt and store secret value
.It Fl l
List all available secret keys
.It Fl v Ar key1 key2 ...
Validate that specified secrets exist and are decryptable
.El
.Sh CONFIGURATION
Configuration is read from
.Pa rsecret.conf
in the same directory as the routes file.
.Pp
Example configuration:
.Bd -literal -offset indent
redis_host=127.0.0.1
redis_port=6379
redis_db=0
timeout_ms=5000
.Ed
.Sh INTEGRATION WITH RSET
Secrets are referenced in PLN files using the syntax
.Ql {{secret:key_name}} .
When
.Xr rset 1
is run with the
.Fl s
flag, these patterns are replaced with decrypted values from Redis.
.Sh EXAMPLES
Store a database password:
.Bd -literal -offset indent
rsecret -s db_password "my_secret_password"
.Ed
.Pp
Retrieve a secret:
.Bd -literal -offset indent
rsecret -g db_password
.Ed
.Pp
Validate multiple secrets:
.Bd -literal -offset indent
rsecret -v db_password api_key ssl_cert
.Ed
.Sh FILES
.Bl -tag -width Ds
.It Pa rsecret.conf
Configuration file
.El
.Sh SEE ALSO
.Xr rset 1 ,
.Xr pln 5 ,
.Xr gpg 1